name: dio_extended
description: a thin wrapper over the dio HTTP client that simplifies networking in Flutter.
version: 1.0.7
repository: https://github.com/anonimeact/diox-dio_extended.git
environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

# Add regular dependencies here.
dependencies:
  chucker_flutter: ^1.8.5
  dio: ^5.9.0
  flutter:
    sdk: flutter
  shake: ^3.0.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6

flutter:
  uses-material-design: true

platforms:
  ? android
  ? ios
  ? web