name: dio_extended
description: A powerful extension library for Dio that simplifies API handling, with clean error management, base service structure, and customizable interceptors.
version: 1.0.2
repository: https://github.com/anonimeact/diox-dio_extended.git
environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

# Add regular dependencies here.
dependencies:
  chucker_flutter: ^1.8.5
  dio: ^5.9.0
  flutter:
    sdk: flutter
  shake: ^3.0.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6

flutter:
  uses-material-design: true
